[package]
name = "color-server"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
cpal = "0.15"
rustfft = "6.2.0"
palette = "0.7.6"

[profile.release]
opt-level = "z"
strip = true
lto = true
panic = "abort"
